[package]
name = "aoc2024-rust"
version = "0.1.0"
edition = "2024"
default-run = "aoc2024-rust"


[dependencies]
reqwest = "0.12.14"
tokio = { version = "1.44.1", features = ["full"] }
regex = "1.10.2"
ndarray = "0.16.1"